import { GiBackwardTime } from "react-icons/gi";
import { GoOrganization } from "react-icons/go";
import {
  LuAlignCenter,
  LuAlignLeft,
  LuAlignRight,
  LuAlignJustify,
  LuArrowDown,
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpDown,
  LuBold,
  LuBookmark,
  LuCalendar,
  LuChartBar,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuCircle,
  LuCircleAlert,
  LuClock,
  LuCog,
  LuDatabase,
  LuDownload,
  LuFolder,
  LuHash,
  LuLayers,
  LuLightbulb,
  LuLink,
  LuEllipsis,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFileText,
  LuFile,
  LuFileSpreadsheet,
  LuFilePlus,
  LuFileUser,
  LuFileCheck,
  LuFilter,
  LuFullscreen,
  LuGripVertical,
  LuHeart,
  LuImageUp,
  LuInbox,
  LuItalic,
  LuKey,
  LuList,
  LuLoaderCircle,
  LuMessageCircle,
  LuMonitorPlay,
  LuMoon,
  LuPanelLeft,
  LuPencil,
  LuPin,
  LuPlus,
  LuRefreshCw,
  LuSearch,
  LuSend,
  LuSettings,
  LuShare2,
  LuShield,
  LuStar,
  LuStrikethrough,
  LuSun,
  LuTag,
  LuThumbsUp,
  LuTrash,
  LuTriangleAlert,
  LuUnderline,
  LuUserCheck,
  LuWrench,
  LuX,
  LuZoomIn,
  LuZoomOut,
  LuCircleCheck,
  LuCircleX,
  LuFileSearch,
  LuBox,
  LuUser,
} from "react-icons/lu";
import { PiHandsClappingLight } from "react-icons/pi";
import {
  TbBook,
  TbBook2,
  TbBookUpload,
  TbDotsVertical,
  TbFileText,
  TbListDetails,
  TbLogout,
  TbReport,
  TbUsers,
  TbUsersGroup,
} from "react-icons/tb";

/**
 * Sistemdeki mevcut iconların listesini görüntülemek için aşşağıdaki link incelenmelidir.
 *
 * NOT: Duplicate bir icon eklememek ve var olan bir iconu ezmemek için eklemeden önce incelenmelidir.
 * NOT2: label propertysi uniq olmalıdır.
 */
export const iconList = [
  { label: "plus", icon: LuPlus },
  { label: "search", icon: LuSearch },
  { label: "grip-vertical", icon: LuGripVertical },
  { label: "x", icon: LuX },
  { label: "dots-vertical", icon: TbDotsVertical },
  { label: "logout", icon: TbLogout },
  { label: "panel-left", icon: LuPanelLeft },
  { label: "check", icon: LuCheck },
  { label: "chevron-right", icon: LuChevronRight },
  { label: "circle", icon: LuCircle },
  { label: "sun", icon: LuSun },
  { label: "moon", icon: LuMoon },
  { label: "users", icon: TbUsers },
  { label: "user", icon: LuUser },
  { label: "users-group", icon: TbUsersGroup },
  { label: "list-details", icon: TbListDetails },
  { label: "report", icon: TbReport },
  { label: "book", icon: TbBook },
  { label: "book-2", icon: TbBook2 },
  { label: "book-upload", icon: TbBookUpload },
  { label: "file-text", icon: TbFileText },
  { label: "chevron-up", icon: LuChevronUp },
  { label: "chevron-down", icon: LuChevronDown },
  { label: "arrow-up", icon: LuArrowUp },
  { label: "chevron-left", icon: LuChevronLeft },
  { label: "ellipsis", icon: LuEllipsis },
  { label: "filter", icon: LuFilter },
  { label: "refresh", icon: LuRefreshCw },
  { label: "pin", icon: LuPin },
  { label: "eye", icon: LuEye },
  { label: "eye-off", icon: LuEyeOff },
  { label: "settings", icon: LuSettings },
  { label: "list", icon: LuList },
  { label: "tags", icon: LuTag },
  { label: "file-text", icon: LuFileText },
  { label: "pencil", icon: LuPencil },
  { label: "loader", icon: LuLoaderCircle },
  { label: "trash", icon: LuTrash },
  { label: "shield", icon: LuShield },
  { label: "key", icon: LuKey },
  { label: "alert-triangle", icon: LuTriangleAlert },
  { label: "align-left", icon: LuAlignLeft },
  { label: "align-justify", icon: LuAlignJustify },
  { label: "align-center", icon: LuAlignCenter },
  { label: "align-right", icon: LuAlignRight },
  { label: "monitor-play", icon: LuMonitorPlay },
  { label: "bold", icon: LuBold },
  { label: "italic", icon: LuItalic },
  { label: "underline", icon: LuUnderline },
  { label: "strikethrough", icon: LuStrikethrough },
  { label: "zoom-in", icon: LuZoomIn },
  { label: "zoom-out", icon: LuZoomOut },
  { label: "fullscreen", icon: LuFullscreen },
  { label: "arrow-left", icon: LuArrowLeft },
  { label: "heart", icon: LuHeart },
  { label: "thumbs-up", icon: LuThumbsUp },
  { label: "star", icon: LuStar },
  { label: "calendar", icon: LuCalendar },
  { label: "message-circle", icon: LuMessageCircle },
  { label: "bookmark", icon: LuBookmark },
  { label: "share", icon: LuShare2 },
  { label: "clap", icon: PiHandsClappingLight },
  { label: "refresh-cw", icon: LuRefreshCw },
  { label: "chart-bar", icon: LuChartBar },
  { label: "send", icon: LuSend },
  { label: "arrow-right", icon: LuArrowRight },
  { label: "clock", icon: LuClock },
  { label: "circle-alert", icon: LuCircleAlert },
  { label: "external-link", icon: LuExternalLink },
  { label: "user-check", icon: LuUserCheck },
  { label: "arrow-up-down", icon: LuArrowUpDown },
  { label: "arrow-down", icon: LuArrowDown },
  { label: "image-up", icon: LuImageUp },
  { label: "inbox", icon: LuInbox },
  { label: "download", icon: LuDownload },
  { label: "backward-time", icon: GiBackwardTime },
  { label: "cog", icon: LuCog },
  { label: "wrench", icon: LuWrench },
  { label: "database", icon: LuDatabase },
  { label: "folder", icon: LuFolder },
  { label: "hash", icon: LuHash },
  { label: "layers", icon: LuLayers },
  { label: "lightbulb", icon: LuLightbulb },
  { label: "link", icon: LuLink },
  { label: "check-circle", icon: LuCircleCheck },
  { label: "x-circle", icon: LuCircleX },
  { label: "file-search", icon: LuFileSearch },
  { label: "file", icon: LuFile },
  { label: "file-spreadsheet", icon: LuFileSpreadsheet },
  { label: "file-plus", icon: LuFilePlus },
  { label: "file-user", icon: LuFileUser },
  { label: "file-check", icon: LuFileCheck },
  { label: "organization", icon: GoOrganization },
  { label: "box", icon: LuBox },
] as const;
